SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM((BB.TOTAL_SALES * B.PRICE)) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN (
    SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
    GROUP BY BOOK_ID
) BB ON B.BOOK_ID = BB.BOOK_ID
GROUP BY CATEGORY, AUTHOR_ID
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;