SELECT 
    B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM 
    BOOK B
JOIN 
    AUTHOR A
ON
    B.AUTHOR_ID = A.AUTHOR_ID
JOIN (
    SELECT SUM(SALES) AS SALES, BOOK_ID
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
    GROUP BY BOOK_ID
) S ON B.BOOK_ID = S.BOOK_ID
GROUP BY
    AUTHOR_ID, CATEGORY
ORDER BY
    AUTHOR_ID ASC, CATEGORY DESC;