WITH MILK AS (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk'
)

SELECT Y.CART_ID
FROM (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
) Y
JOIN MILK M ON Y.CART_ID = M.CART_ID
ORDER BY CART_ID ASC;