WITH CART_TABLE AS (
    SELECT DISTINCT CART_ID, NAME
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk' OR NAME = 'Yogurt'
)

SELECT CART_ID
FROM CART_TABLE
GROUP BY CART_ID
HAVING COUNT(*) = 2
ORDER BY CART_ID