SELECT C.ID 
FROM ECOLI_DATA A
JOIN (
    SELECT ID, PARENT_ID
    FROM ECOLI_DATA
) B ON A.ID = B.PARENT_ID
JOIN (
    SELECT ID, PARENT_ID
    FROM ECOLI_DATA
) C ON B.ID = C.PARENT_ID
WHERE A.PARENT_ID IS NULL
ORDER BY ID ASC;