SELECT A.ID, IFNULL(B.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA A
LEFT JOIN (
    SELECT COUNT(*) AS CHILD_COUNT, PARENT_ID
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
) B ON A.ID = B.PARENT_ID 
ORDER BY ID ASC;