# SELECT 
#     DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, 
#     PRODUCT_ID, 
#     USER_ID, 
#     SUM(SALES_AMOUNT) AS SALES_AMOUNT
# FROM ( 
#     SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT 
#     FROM ONLINE_SALE
#     WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
    
#     UNION ALL
    
#     SELECT  SALES_DATE, PRODUCT_ID, 'NULL' AS USER_ID, SALES_AMOUNT 
#     FROM OFFLINE_SALE
#     WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
# ) AS T
# GROUP BY SALES_DATE, PRODUCT_ID, USER_ID
# ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;

SELECT 
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, 
    PRODUCT_ID, 
    USER_ID, 
    SALES_AMOUNT -- SUM을 빼고 그대로 출력
FROM ( 
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT 
    FROM ONLINE_SALE
    WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01'
    
    UNION ALL
    
    SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT -- 따옴표 제거
    FROM OFFLINE_SALE
    WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01'
) AS T
-- GROUP BY가 필요 없는 경우가 많습니다.
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;