SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE * 30 * ((100 - P.DISCOUNT_RATE) * 0.01), 0) AS FEE
FROM (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = 'SUV' OR CAR_TYPE = '세단'
) C

JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
    HAVING COUNT(*) = SUM(CASE WHEN START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01' THEN 0 ELSE 1 END)
) H ON C.CAR_ID = H.CAR_ID

JOIN (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE (CAR_TYPE = '세단' OR CAR_TYPE = 'SUV') AND DURATION_TYPE = '30일 이상'
) P ON C.CAR_TYPE = P.CAR_TYPE
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;