SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE * 30 * P.DISCOUNT_RATE, 0) AS FE
FROM (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '세단' OR CAR_TYPE = 'SUV'
) C
JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE > '2022-11-01' OR (START_DATE BETWEEN '2022-11-01' AND '2022-11-30')
    )
    GROUP BY CAR_ID
) H ON C.CAR_ID = H.CAR_ID

JOIN (
    SELECT CAR_TYPE, (100 - DISCOUNT_RATE) * 0.01 AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
) P ON P.CAR_TYPE = C.CAR_TYPE
HAVING FE BETWEEN 500000 AND 1999999
ORDER BY FE DESC, CAR_TYPE ASC, CAR_ID DESC;