SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO A
JOIN (
    SELECT MAX(FAVORITES) AS MAX_FAVORITES, FOOD_TYPE
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) B ON A.REST_ID = REST_ID
WHERE A.FOOD_TYPE = B.FOOD_TYPE AND A.FAVORITES = B.MAX_FAVORITES
ORDER BY FOOD_TYPE DESC;