WITH MAX_F AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)

SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, B.MAX_FAVORITES
FROM REST_INFO A
JOIN MAX_F B ON A.FOOD_TYPE = B.FOOD_TYPE
WHERE A.FAVORITES = B.MAX_FAVORITES
ORDER BY FOOD_TYPE DESC;