SELECT U.USER_ID, U.NICKNAME, CONCAT(U.CITY, ' ', U.STREET_ADDRESS1, ' ', U.STREET_ADDRESS2) AS '전체주소', 
    CONCAT(SUBSTRING(TLNO, 1, 3), '-', SUBSTRING(TLNO, 4, 4), '-', SUBSTRING(TLNO, 8, 4)) AS '전화번호'
FROM USED_GOODS_USER U
JOIN (
    SELECT COUNT(*) AS COUNT_BOARD, WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
) B ON B.WRITER_ID = U.USER_ID
WHERE B.COUNT_BOARD >= 3
ORDER BY USER_ID DESC;