SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM (
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
    FROM ANIMAL_OUTS
    WHERE SEX_UPON_OUTCOME LIKE 'Spayed%' OR SEX_UPON_OUTCOME LIKE 'Neutered%'
) O
JOIN (
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE NOT LIKE 'Spayed%' AND SEX_UPON_INTAKE NOT LIKE 'Neutered%'
)I ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY ANIMAL_ID ASC;