SELECT S.YEAR, S.MONTH, I.GENDER, COUNT(*) AS USERS
FROM (
    SELECT USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
    FROM ONLINE_SALE
    GROUP BY USER_ID, YEAR, MONTH 
) S
JOIN (
    SELECT USER_ID, GENDER
    FROM USER_INFO
    WHERE GENDER IS NOT NULL
) I ON S.USER_ID = I.USER_ID
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC;