SELECT
    O.YEAR, O.MONTH, U.GENDER, COUNT(DISTINCT O.USER_ID) AS USERS
FROM 
    USER_INFO U
JOIN (
    SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, USER_ID
    FROM ONLINE_SALE
) O ON O.USER_ID = U.USER_ID
WHERE 
    GENDER IS NOT NULL
GROUP BY
    YEAR, MONTH, GENDER
ORDER BY
    YEAR ASC, MONTH ASC, GENDER ASC;