SELECT O.YEAR, O.MONTH, I.GENDER, COUNT(*)
FROM (
    SELECT USER_ID, GENDER
    FROM USER_INFO
    WHERE GENDER IS NOT NULL
) I
JOIN (
    SELECT USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
    FROM ONLINE_SALE 
    GROUP BY USER_ID, YEAR, MONTH
) O ON O.USER_ID = I.USER_ID
GROUP BY GENDER, YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC;