WITH IS_NAME AS (
    SELECT O.ANIMAL_ID
    FROM ANIMAL_OUTS O
    JOIN ANIMAL_INS I ON I.ANIMAL_ID = O.ANIMAL_ID
)

SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM IS_NAME)
ORDER BY ANIMAL_ID ASC;