WITH COUNT_USER AS (
    SELECT COUNT(*) AS COUNT_USERS
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

SELECT 
    YEAR, 
    MONTH,
    COUNT(*) AS PURCHASED_USERS,
    ROUND(COUNT(*) / C.COUNT_USERS, 1) AS PUCHASED_RATIO
FROM 
    (
        SELECT USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
        FROM ONLINE_SALE
        GROUP BY USER_ID, YEAR, MONTH
    ) O
JOIN (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
    GROUP BY USER_ID
) U ON O.USER_ID = U.USER_ID
JOIN COUNT_USER C
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC;