WITH NEW_ONLINE AS (
    SELECT USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
    FROM ONLINE_SALE
    GROUP BY USER_ID, YEAR, MONTH
)

SELECT O.YEAR, O.MONTH, O.PURCHASED_USERS, ROUND(O.PURCHASED_USERS / U.TOTAL_USERS, 1) AS PUCHASED_RATIO
FROM (
    SELECT USER_ID, COUNT(*) AS TOTAL_USERS
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
) U
JOIN (    
    SELECT USER_ID, YEAR, MONTH, COUNT(*) AS PURCHASED_USERS
    FROM NEW_ONLINE
    WHERE USER_ID IN (SELECT USER_ID FROM USER_INFO WHERE YEAR(JOINED) = 2021)
    GROUP BY YEAR, MONTH
) O
ORDER BY YEAR ASC, MONTH ASC