WITH RECURSIVE GENERATION_TABLE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, G.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN GENERATION_TABLE G ON E.PARENT_ID = G.ID
)

SELECT COUNT(*) AS COUNT, G.GENERATION
FROM GENERATION_TABLE G
LEFT JOIN (
    SELECT ID, PARENT_ID
    FROM ECOLI_DATA
) E ON  E.PARENT_ID = G.ID
WHERE E.PARENT_ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION ASC