WITH CAR_A AS (
    SELECT CAR_ID, COUNT(*) AS A_COUNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE > '2022-10-16' OR END_DATE < '2022-10-16'
    GROUP BY CAR_ID
),

CAR_B AS (
    SELECT CAR_ID, COUNT(*) AS B_COUNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
)

SELECT A.CAR_ID, 
    CASE WHEN A.A_COUNT = B.B_COUNT THEN '대여 가능'
    ELSE '대여중'
    END AS 'AVAILABILITY'
FROM CAR_A A
JOIN CAR_B B ON A.CAR_ID = B.CAR_ID
ORDER BY CAR_ID DESC;