WITH COUNT_TABLE_A AS (
    SELECT CAR_ID, COUNT(*) AS COUNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' < START_DATE OR END_DATE < '2022-10-16'
    GROUP BY CAR_ID
),

COUNT_TABLE_B AS (
    SELECT CAR_ID, COUNT(*) AS COUNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
)

SELECT 
    A.CAR_ID,
    CASE
        WHEN A.COUNT = B.COUNT THEN '대여 가능'
        ELSE '대여중' END AS AVAILABILITY
FROM COUNT_TABLE_A A
JOIN COUNT_TABLE_B B ON A.CAR_ID = B.CAR_ID
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;