SELECT 
    A.ID, A.NAME, A.HOST_ID
FROM 
    PLACES A
JOIN   
    (
        SELECT COUNT(*) AS COUNT_ADD_SERVICE, HOST_ID
        FROM PLACES
        GROUP BY HOST_ID
        HAVING COUNT_ADD_SERVICE >= 2
    ) B ON A.HOST_ID = B.HOST_ID
ORDER BY 
    ID ASC;