SELECT 
    H.HISTORY_ID, ROUND(P.DISCOUNT_RATE * C.DAILY_FEE * H.DATE_DIFF, 0) AS FEE
FROM(
    SELECT
        HISTORY_ID,
        CAR_ID,
        CASE 
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE '7일 미만' END DURATION_TYPE,
        DATEDIFF(END_DATE, START_DATE) + 1 AS DATE_DIFF
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) H
JOIN (
    SELECT DURATION_TYPE, (100 - DISCOUNT_RATE) * 0.01 AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
    
    UNION ALL
    
    SELECT '7일 미만' AS DURATION_TYPE, 1 AS DISCOUNT_RATE
) P ON H.DURATION_TYPE = P.DURATION_TYPE
JOIN (
    SELECT CAR_ID, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '트럭'
) C ON H.CAR_ID = C.CAR_ID
ORDER BY FEE DESC, HISTORY_ID DESC;