SELECT F.FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS A_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
) F
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS B_ORDER
    FROM JULY
    GROUP BY FLAVOR
) J ON F.FLAVOR = J.FLAVOR
ORDER BY F.A_ORDER + J.B_ORDER DESC
LIMIT 3;

