SELECT
    F.FLAVOR
FROM 
    FIRST_HALF F
JOIN (
    SELECT SUM(TOTAL_ORDER) AS TOTAL_ORDER, FLAVOR
    FROM JULY
    GROUP BY FLAVOR
) J ON F.FLAVOR = J.FLAVOR
ORDER BY
    F.TOTAL_ORDER + J.TOTAL_ORDER DESC
LIMIT 
    3;
