WITH RECURSIVE HOUR_LIST AS (
    SELECT 0 AS HOUR 
    UNION ALL
    SELECT HOUR + 1
    FROM HOUR_LIST
    WHERE HOUR < 23
)

SELECT H.HOUR, COUNT(HOUR(A.DATETIME)) AS COUNT
FROM HOUR_LIST H
LEFT JOIN ANIMAL_OUTS A ON H.HOUR = HOUR(A.DATETIME)
GROUP BY HOUR
ORDER BY HOUR ASC;