WITH RECURSIVE TIME_TABLE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM TIME_TABLE
    WHERE HOUR < 23
)

SELECT T.HOUR, IFNULL(O.HOUR_COUNT, 0) AS COUNT
FROM TIME_TABLE T
LEFT JOIN (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS HOUR_COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR
) O ON T.HOUR = O.HOUR
ORDER BY HOUR ASC;