WITH RECURSIVE HOUR_TABLE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM HOUR_TABLE
    WHERE HOUR < 23
)

SELECT H.HOUR, IFNULL(C.COUNT, 0) AS COUNT
FROM HOUR_TABLE H
LEFT JOIN (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR
) C ON H.HOUR = C.HOUR
ORDER BY HOUR ASC;