SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
JOIN (
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
) S ON D.SKILL_CODE & S.CODE > 0
GROUP BY ID, EMAIL, FIRST_NAME, LAST_NAME
ORDER BY ID ASC;