SELECT 
    M.MEMBER_NAME, RR.REVIEW_TEXT, RR.REVIEW_DATE
FROM 
    MEMBER_PROFILE M
JOIN (
    SELECT MEMBER_ID, COUNT(*) AS COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT DESC
    LIMIT 1
) R ON M.MEMBER_ID = R.MEMBER_ID
JOIN (
    SELECT REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE, MEMBER_ID
    FROM REST_REVIEW
) RR ON M.MEMBER_ID = RR.MEMBER_ID
ORDER BY
    REVIEW_DATE ASC, REVIEW_TEXT ASC;