WITH MAX_REVIEW_TABLE AS (
    SELECT MEMBER_ID, COUNT(*) AS COUNT
    FROM  REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT DESC
    LIMIT 1
)

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M
JOIN (
    SELECT MEMBER_ID, REVIEW_TEXT, REVIEW_DATE
    FROM REST_REVIEW
    WHERE MEMBER_ID IN (SELECT MEMBER_ID FROM MAX_REVIEW_TABLE)
) R ON M.MEMBER_ID = R.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;