SELECT 
    MONTH(A.START_DATE) AS MONTH, A.CAR_ID, COUNT(*) AS RECORDS
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY A
JOIN
    (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
        GROUP BY CAR_ID
        HAVING COUNT(*) >= 5
    ) B ON A.CAR_ID = B.CAR_ID
WHERE 
    MONTH(A.START_DATE) BETWEEN 8 AND 10
GROUP BY
    MONTH, CAR_ID
HAVING
    RECORDS > 0
ORDER BY
    MONTH ASC, CAR_ID DESC;