SELECT A.CAR_ID
FROM (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '세단'
) A
JOIN (
    SELECT DISTINCT(CAR_ID)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) = 10
) B ON A.CAR_ID = B.CAR_ID
ORDER BY CAR_ID DESC;