SELECT H.CAR_ID
FROM (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) = 10
) H
JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '세단'
) C ON C.CAR_ID = H.CAR_ID
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;