SELECT 
    A.ID, N.FISH_NAME, B.LENGTH
FROM 
    FISH_INFO A
JOIN (
    SELECT
        FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM 
        FISH_INFO
    GROUP BY 
        FISH_TYPE
) B ON A.FISH_TYPE = B.FISH_TYPE AND A.LENGTH = B.LENGTH
JOIN 
    FISH_NAME_INFO N
ON
    A.FISH_TYPE = N.FISH_TYPE
ORDER BY
    A.ID ASC;