SELECT A.ID, N.FISH_NAME, A.LENGTH
FROM FISH_INFO A
JOIN 
    (
        SELECT MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
        FROM FISH_INFO
        GROUP BY FISH_TYPE
    ) B ON A.LENGTH = B.MAX_LENGTH AND A.FISH_TYPE = B.FISH_TYPE
JOIN FISH_NAME_INFO N ON A.FISH_TYPE = N.FISH_TYPE
ORDER BY ID ASC;