WITH MAX_SIZE AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT A.ID, C.FISH_NAME, B.MAX_LENGTH AS LENGTH
FROM FISH_INFO A
JOIN MAX_SIZE B ON A.FISH_TYPE = B.FISH_TYPE AND A.LENGTH = B.MAX_LENGTH
JOIN FISH_NAME_INFO C ON A.FISH_TYPE = C.FISH_TYPE
ORDER BY ID ASC;