SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN (
    SELECT BOOK_ID, SALES
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
) S ON B.BOOK_ID = S.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY CATEGORY ASC