WITH MAX_TABLE AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY LIKE '과자' OR CATEGORY LIKE '국' OR CATEGORY LIKE '김치' OR CATEGORY LIKE '식용유'
    GROUP BY CATEGORY
)

SELECT M.CATEGORY, M.MAX_PRICE, F.PRODUCT_NAME
FROM MAX_TABLE M
JOIN FOOD_PRODUCT F
ON M.CATEGORY = F.CATEGORY AND M.MAX_PRICE = F.PRICE
ORDER BY MAX_PRICE DESC;