# WITH FISH_MAX AS (
#     SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
#     FROM FISH_INFO
#     GROUP BY FISH_TPYE
# )

SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(IFNULL(LENGTH, 10)) >= 33
ORDER BY FISH_TYPE ASC;