SELECT
    COUNT(*) AS FISH_COUNT, MAX(A.LENGTH) AS MAX_LENGTH, A.FISH_TYPE
FROM 
    FISH_INFO A
JOIN 
    (
        SELECT AVG(IFNULL(LENGTH, 10)) AS AVG_LENGTH, FISH_TYPE
        FROM FISH_INFO
        GROUP BY FISH_TYPE
        HAVING AVG_LENGTH >= 33
    ) B ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY 
    FISH_TYPE
ORDER BY 
    FISH_TYPE ASC;