SELECT
    CASE
        WHEN 'PYTHON' IN (SELECT NAME FROM SKILLCODES WHERE CODE & D.SKILL_CODE > 0) AND
            'Front End' IN (SELECT CATEGORY FROM SKILLCODES WHERE CODE & D.SKILL_CODE > 0) THEN 'A'
        WHEN 'C#' IN (SELECT NAME FROM SKILLCODES WHERE CODE & D.SKILL_CODE > 0) THEN 'B'
        WHEN 'Front End' IN (SELECT CATEGORY FROM SKILLCODES WHERE CODE & D.SKILL_CODE > 0) THEN 'C'
    END AS GRADE,
    D.ID, D.EMAIL
FROM DEVELOPERS D
HAVING GRADE IS NOT NULL
ORDER BY GRADE ASC, ID ASC;