WITH DEVELOPER_SKILLS AS (
    SELECT
        D.ID,
        D.EMAIL,
        MAX(CASE WHEN S.NAME = 'Python' THEN 1 ELSE 0 END) AS HAS_PYTHON,
        MAX(CASE WHEN S.NAME = 'C#' THEN 1 ELSE 0 END) AS HAS_CSHARP,
        MAX(CASE WHEN S.CATEGORY = 'Front End' THEN 1 ELSE 0 END) AS HAS_FE
    FROM DEVELOPERS D
    JOIN SKILLCODES S ON (D.SKILL_CODE & S.CODE) > 0
    GROUP BY D.ID, D.EMAIL
)

SELECT 
    CASE
        WHEN HAS_PYTHON = 1 AND HAS_FE = 1 THEN 'A'
        WHEN HAS_CSHARP = 1 THEN 'B'
        WHEN HAS_FE = 1 THEN 'C'
        ELSE NULL
        END AS GRADE,
    ID,
    EMAIL
FROM DEVELOPER_SKILLS
HAVING GRADE IS NOT NULL
ORDER BY GRADE ASC, ID ASC;